name: Deploy Infra

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  IAM_ROLE: arn:aws:iam::160071257600:role/jijun6-github-actions-role

jobs:

  # Can add extra jobs/steps to run any pre deploy tasks

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@2ec54502e3e7b5d9591613811da6daded35caa19
        with:
          role-session-name: GitHubActionsSession
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get aws identity
        run: |
          aws sts get-caller-identity      

      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y terraform

      - name: Terraform Init
        run: terraform init
        working-directory: ./Session_6_Terraform_Cloud_and_Pipelines/terraform

      - name: Terraform Plan
        run: terraform plan -var-file=dev.tfvars
        working-directory: ./Session_6_Terraform_Cloud_and_Pipelines/terraform

      - name: Terraform Apply
        run: terraform apply -var-file=dev.tfvars -auto-approve
        working-directory: ./Session_6_Terraform_Cloud_and_Pipelines/terraform
        timeout-minutes: 20

      # Can add extra steps to run Terraform to create the AWS resources
